=head1 NAME

virt-p2v-make-disk - Build the virt-p2v disk using virt-builder

=head1 SYNOPSIS

 virt-p2v-make-disk -o /dev/sdX [os-version]

=head1 DESCRIPTION

L<virt-p2v(1)> converts a physical machine to run virtualized on KVM,
managed by libvirt, OpenStack, oVirt, Red Hat Enterprise
Virtualisation (RHEV), or one of the other targets supported by
L<virt-v2v(1)>.

virt-p2v-make-disk is a script which creates a bootable disk image or
USB key containing virt-p2v.  It uses L<virt-builder(1)> to do this,
and is just a small shell script around virt-builder.

The required I<-o> parameter specifies where the output should go, for
example to a USB key (eg. C<-o /dev/sdX>) or to a file.  If you pass a
device name, then B<the existing contents of the device will be erased>.

=head2 C<os-version> parameter

The optional C<os-version> parameter is the base Linux distro to use
for the operating system on the ISO.  If you don't set this parameter,
the script tries to choose a suitable default for you.  Most users
should I<not> use the C<os-version> parameter.

The base OS selected for virt-p2v is not related in any way to the OS
of the physical machine that you are trying to convert.

To list possible C<os-version> combinations, do:

 virt-builder -l

=head1 EXAMPLES

Write a virt-p2v bootable USB key on F</dev/sdX> (any existing content
on F</dev/sdX> is erased):

 virt-p2v-make-disk -o /dev/sdX

Write a virt-p2v bootable virtual disk image, and boot it under qemu:

 virt-p2v-make-disk -o /var/tmp/p2v.img
 qemu-kvm -m 1024 -boot c \
   -drive file=/var/tmp/p2v.img,if=virtio,index=0 \
   -drive file=/var/tmp/guest.img,if=virtio,index=1

where F</var/tmp/guest.img> would be the disk image of some guest that
you want to convert (for testing only).

=head1 ADDING AN SSH IDENTITY

You can inject an SSH identity (private key) file to the image using
the I<--inject-ssh-identity> option.

First create a key pair.  It must have an empty passphrase:

 ssh-keygen -t rsa -N '' -f id_rsa

This creates a private key (C<id_rsa>) and a public key
(C<id_rsa.pub>) pair.  The public key should be appended to the
C<authorized_keys> file on the virt-v2v conversion server (usually to
C</root/.ssh/authorized_keys>).

The private key should be injected into the disk image and then
discarded:

 virt-p2v-make-disk [...] --inject-ssh-identity id_rsa
 rm id_rsa

When booting virt-p2v, specify the URL of the injected file like this:

 │         User name: [root_____________________________] │
 │                                                        │
 │          Password: [    <leave this field blank>     ] │
 │                                                        │
 │  SSH Identity URL: [file:///var/tmp/id_rsa___________] │

or if using the kernel command line, add:

 p2v.identity=file:///var/tmp/id_rsa

For more information, see L<virt-p2v(1)/SSH IDENTITIES>.

=head1 OPTIONS

=over 4

=item B<--help>

Display help.

=item B<--inject-ssh-identity> id_rsa

Add an SSH identity (private key) file into the image.
See L</ADDING AN SSH IDENTITY> above.

=item B<-o> OUTPUT

=item B<--output> OUTPUT

Write output to C<OUTPUT>, which can be a local file or block device.
B<The existing contents of the device will be erased>.

=item B<-V>

=item B<--version>

Display version number and exit.

=back

=head1 FILES

=over 4

=item F<$libexecdir/virt-p2v>

The L<virt-p2v(1)> binary which is copied into the bootable disk
image.

The location of the binary can be changed by setting the
C<VIRT_P2V_DATA_DIR> environment variable.

=item F<$datadir/virt-p2v/issue>

=item F<$datadir/virt-p2v/launch-virt-p2v.in>

=item F<$datadir/virt-p2v/p2v.service>

Various data files that are copied into the bootable disk image.

The location of these files can be changed by setting the
C<VIRT_P2V_DATA_DIR> environment variable.

=back

=head1 ENVIRONMENT VARIABLES

=over 4

=item C<VIRT_P2V_DATA_DIR>

The directory where virt-p2v-make-disk looks for data files (see
L</FILES> above).  If not set, a compiled-in location is used.

=back

=head1 SEE ALSO

L<virt-p2v(1)>,
L<virt-p2v-make-kickstart(1)>,
L<virt-v2v(1)>,
L<http://libguestfs.org/>.

=head1 AUTHORS

Richard W.M. Jones L<http://people.redhat.com/~rjones/>

=head1 COPYRIGHT

Copyright (C) 2009-2016 Red Hat Inc.
