#!/bin/sh

usage() {
  echo >&2 "\
Usage: $0 [OPTION]...
Bootstrap this package from the checked-out sources.
"
}

for option
do
  case $option in
  --help)
    usage
    exit;;
  *)
    echo >&2 "$0: $option: unknown option"
    exit 1;;
  esac
done

# Get gnulib files.

echo "$0: getting gnulib files..."
git submodule init || exit $?
git submodule update || exit $?
GNULIB_SRCDIR=.gnulib

ls po/*.po 2>/dev/null | sed 's|.*/||; s|\.po$||' > po/LINGUAS

# Run autopoint, to get po/Makevars.template:
# Also, released autopoint has the tendency to install macros that have
# been obsoleted in current gnulib, so run this before gnulib-tool.
autopoint --force

# Autoreconf runs aclocal before libtoolize, which causes spurious
# warnings if the initial aclocal is confused by the libtoolized
# (or worse out-of-date) macro directory.
libtoolize --copy --install

gnulib_tool=$GNULIB_SRCDIR/gnulib-tool
<$gnulib_tool || exit

(cd daemon && mkdir -p tests lib && ../$gnulib_tool --update)

modules='
arpa_inet
c-ctype
closeout
error
filevercmp
fts
full-read
full-write
gitlog-to-changelog
gnu-make
gnumakefile
hash
hash-pjw
ignore-value
lock
maintainer-makefile
manywarnings
netinet_in
progname
setenv
strchrnul
strerror
strndup
vasprintf
vc-list-files
warnings
xalloc
xalloc-die
xstrtol
xstrtoll
xvasprintf
'

$gnulib_tool			\
  --avoid=dummy			\
  --with-tests			\
  --m4-base=m4			\
  --source-base=gnulib/lib	\
  --tests-base=gnulib/tests	\
  --import $modules

# Disable autopoint and libtoolize, since they were already done above.
AUTOPOINT=true LIBTOOLIZE=true autoreconf --verbose --install
