#!/usr/bin/perl
# virt-rescue
# Copyright (C) 2009 Red Hat Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

# This script sets up the environment so you can run virt-rescue in
# place without needing to do 'make install' first. You can also run
# virt-rescue by creating a symlink to this script and putting it in
# your path.
#
# Use it like this:
#   ./run-rescue-locally [usual virt-rescue args ...]

use strict;
use warnings;

use File::Basename qw(dirname);
use File::Spec;
use Cwd qw(abs_path);

my $path = $0;

# Follow symlinks until we get to the real file
while(-l $path) {
    my $link = readlink($path) or die "readlink: $path: $!";
    if(File::Spec->file_name_is_absolute($link)) {
        $path = $link;
    } else {
        $path = File::Spec->catfile(dirname($path), $link);
    }
}

# Get the absolute path of the parent directory
$path = abs_path(dirname($path).'/..');

$ENV{LD_LIBRARY_PATH} = $path.'/src/.libs';
$ENV{LIBGUESTFS_PATH} = $path.'/appliance';
$ENV{PERL5LIB}        = $path.'/perl/blib/lib:'.$path.'/perl/blib/arch';

exec('perl', $path.'/rescue/virt-rescue', @ARGV);
