/* libguestfs generated file
 * WARNING: THIS FILE IS GENERATED BY 'src/generator.ml'.
 * ANY CHANGES YOU MAKE TO THIS FILE WILL BE LOST.
 *
 * Copyright (C) 2009 Red Hat Inc.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
 */

#include <stdio.h>
#include <stdlib.h>

#include <guestfs.h>

#include <caml/config.h>
#include <caml/alloc.h>
#include <caml/callback.h>
#include <caml/fail.h>
#include <caml/memory.h>
#include <caml/mlvalues.h>

#include "guestfs_c.h"

CAMLprim value
ocaml_guestfs_launch (value hv /* XXX */)
{
  CAMLparam1 (hv); /* XXX */
/* XXX write something here */
  CAMLreturn (Val_unit); /* XXX */
}

CAMLprim value
ocaml_guestfs_wait_ready (value hv /* XXX */)
{
  CAMLparam1 (hv); /* XXX */
/* XXX write something here */
  CAMLreturn (Val_unit); /* XXX */
}

CAMLprim value
ocaml_guestfs_kill_subprocess (value hv /* XXX */)
{
  CAMLparam1 (hv); /* XXX */
/* XXX write something here */
  CAMLreturn (Val_unit); /* XXX */
}

CAMLprim value
ocaml_guestfs_add_drive (value hv /* XXX */)
{
  CAMLparam1 (hv); /* XXX */
/* XXX write something here */
  CAMLreturn (Val_unit); /* XXX */
}

CAMLprim value
ocaml_guestfs_add_cdrom (value hv /* XXX */)
{
  CAMLparam1 (hv); /* XXX */
/* XXX write something here */
  CAMLreturn (Val_unit); /* XXX */
}

CAMLprim value
ocaml_guestfs_config (value hv /* XXX */)
{
  CAMLparam1 (hv); /* XXX */
/* XXX write something here */
  CAMLreturn (Val_unit); /* XXX */
}

CAMLprim value
ocaml_guestfs_set_path (value hv /* XXX */)
{
  CAMLparam1 (hv); /* XXX */
/* XXX write something here */
  CAMLreturn (Val_unit); /* XXX */
}

CAMLprim value
ocaml_guestfs_get_path (value hv /* XXX */)
{
  CAMLparam1 (hv); /* XXX */
/* XXX write something here */
  CAMLreturn (Val_unit); /* XXX */
}

CAMLprim value
ocaml_guestfs_set_autosync (value hv /* XXX */)
{
  CAMLparam1 (hv); /* XXX */
/* XXX write something here */
  CAMLreturn (Val_unit); /* XXX */
}

CAMLprim value
ocaml_guestfs_get_autosync (value hv /* XXX */)
{
  CAMLparam1 (hv); /* XXX */
/* XXX write something here */
  CAMLreturn (Val_unit); /* XXX */
}

CAMLprim value
ocaml_guestfs_set_verbose (value hv /* XXX */)
{
  CAMLparam1 (hv); /* XXX */
/* XXX write something here */
  CAMLreturn (Val_unit); /* XXX */
}

CAMLprim value
ocaml_guestfs_get_verbose (value hv /* XXX */)
{
  CAMLparam1 (hv); /* XXX */
/* XXX write something here */
  CAMLreturn (Val_unit); /* XXX */
}

CAMLprim value
ocaml_guestfs_mount (value hv /* XXX */)
{
  CAMLparam1 (hv); /* XXX */
/* XXX write something here */
  CAMLreturn (Val_unit); /* XXX */
}

CAMLprim value
ocaml_guestfs_sync (value hv /* XXX */)
{
  CAMLparam1 (hv); /* XXX */
/* XXX write something here */
  CAMLreturn (Val_unit); /* XXX */
}

CAMLprim value
ocaml_guestfs_touch (value hv /* XXX */)
{
  CAMLparam1 (hv); /* XXX */
/* XXX write something here */
  CAMLreturn (Val_unit); /* XXX */
}

CAMLprim value
ocaml_guestfs_cat (value hv /* XXX */)
{
  CAMLparam1 (hv); /* XXX */
/* XXX write something here */
  CAMLreturn (Val_unit); /* XXX */
}

CAMLprim value
ocaml_guestfs_ll (value hv /* XXX */)
{
  CAMLparam1 (hv); /* XXX */
/* XXX write something here */
  CAMLreturn (Val_unit); /* XXX */
}

CAMLprim value
ocaml_guestfs_ls (value hv /* XXX */)
{
  CAMLparam1 (hv); /* XXX */
/* XXX write something here */
  CAMLreturn (Val_unit); /* XXX */
}

CAMLprim value
ocaml_guestfs_list_devices (value hv /* XXX */)
{
  CAMLparam1 (hv); /* XXX */
/* XXX write something here */
  CAMLreturn (Val_unit); /* XXX */
}

CAMLprim value
ocaml_guestfs_list_partitions (value hv /* XXX */)
{
  CAMLparam1 (hv); /* XXX */
/* XXX write something here */
  CAMLreturn (Val_unit); /* XXX */
}

CAMLprim value
ocaml_guestfs_pvs (value hv /* XXX */)
{
  CAMLparam1 (hv); /* XXX */
/* XXX write something here */
  CAMLreturn (Val_unit); /* XXX */
}

CAMLprim value
ocaml_guestfs_vgs (value hv /* XXX */)
{
  CAMLparam1 (hv); /* XXX */
/* XXX write something here */
  CAMLreturn (Val_unit); /* XXX */
}

CAMLprim value
ocaml_guestfs_lvs (value hv /* XXX */)
{
  CAMLparam1 (hv); /* XXX */
/* XXX write something here */
  CAMLreturn (Val_unit); /* XXX */
}

CAMLprim value
ocaml_guestfs_pvs_full (value hv /* XXX */)
{
  CAMLparam1 (hv); /* XXX */
/* XXX write something here */
  CAMLreturn (Val_unit); /* XXX */
}

CAMLprim value
ocaml_guestfs_vgs_full (value hv /* XXX */)
{
  CAMLparam1 (hv); /* XXX */
/* XXX write something here */
  CAMLreturn (Val_unit); /* XXX */
}

CAMLprim value
ocaml_guestfs_lvs_full (value hv /* XXX */)
{
  CAMLparam1 (hv); /* XXX */
/* XXX write something here */
  CAMLreturn (Val_unit); /* XXX */
}

