#!/bin/bash -
# Copyright (C) 2009-2010 Red Hat Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

set -e

# This script adds a new node under \Microsoft in an existing software
# hive.

if [ $# -ne 2 ]; then
    echo "$0 software software.new"
    exit 1
fi

d=`dirname $0`

$d/hivexsh -w <<EOF
load $1
cd \Microsoft
add TestNode
cd TestNode
add Test1
add Test2
add Test3
add Test4
add Test5
cd Test1
setval 2
@
string:This is the default key of Test1
ThisIsTest1
dword:0x12345678
cd ..
cd Test5
setval 2
@
string:This is the default key of Test5
ThisIsTest5
dword:0x87654321
commit $2
EOF