#!/bin/bash -
# Copyright (C) 2009-2010 Red Hat Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

set -e

if [ $# -lt 2 -o $# -gt 3 ]; then
    echo "hivexget hivefile path [key]"
    exit 1
fi

if [ $# -eq 2 ]; then
    hivexsh <<EOF
load $1
cd $2
lsval
exit
EOF
else
    key=$3
    if [ "$key" = "" ]; then
        key="@"
    fi
    hivexsh <<EOF
load $1
cd $2
lsval $key
exit
EOF
fi
