#!/bin/sh -
# libguestfs Perl bindings
# Copyright (C) 2009-2016 Red Hat Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

errors=0

guestsdir="$(cd ../test-data/phony-guests && pwd)"
export guestsdir

for f in $srcdir/t/*.py; do
  $PYTHON $f
  r=$?
  case $r in
      0) ;;
      77)
          echo "$f: test skipped"
          ;;
      *)
          echo "FAIL: $f"
          ((errors++))
          ;;
  esac
done

if [ $errors -gt 0 ]; then
    exit 1
fi
