#!/bin/sh -
# libguestfs inspector
# Copyright (C) 2009 Red Hat Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

# This script sets up the environment so you can run
# virt-inspector from the top-level source directory
# without needing to do 'make install' first.
#
# Use it like this:
#   ./inspector/run-inspector-locally [usual virt-inspector args ...]

export LD_LIBRARY_PATH=$(pwd)/src/.libs
export LIBGUESTFS_PATH=$(pwd)
export PERL5LIB=$(pwd)/perl/blib/lib:$(pwd)/perl/blib/arch
perl ./inspector/virt-inspector.pl "$@"
